# Generated by Django 4.1.1 on 2022-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tugilgan_yil', models.DateField(max_length=50)),
                ('tirik', models.BooleanField(default=True)),
                ('kitoblar_soni', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
