# Generated by Django 4.1.1 on 2022-09-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_record_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.BooleanField(default=False),
        ),
    ]
