# Generated by Django 4.1.1 on 2022-09-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_kitob_muallif_alter_record_kitob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='kitob',
        ),
        migrations.RemoveField(
            model_name='record',
            name='student',
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Muallif',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
