# Generated by Django 4.1.1 on 2022-09-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='kitob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
