# Generated by Django 4.1.1 on 2022-09-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_kitob_muallif_alter_record_kitob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.muallif'),
        ),
        migrations.AlterField(
            model_name='record',
            name='kitob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.kitob'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.student'),
        ),
    ]
