# Generated by Django 4.1.1 on 2022-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_kitob_muallif_alter_record_kitob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='kitob_soni',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
